package modelo;
// Generated 1 feb. 2021 18:32:53 by Hibernate Tools 5.4.21.Final

import java.util.Date;

/**
 * Datos generated by hbm2java
 */
public class Datos implements java.io.Serializable {

	private Integer codDatos;
	private Estaciones estaciones;
	private Date fecha;
	private Date hora;
	private Double comgm3;
	private Double co8hmgm3;
	private Double nogm3;
	private Double no2;
	private String no2ica;
	private Double noxgm3;
	private Double pm10;
	private String pm10ica;
	private Double pm25;
	private String pm25ica;
	private Double so2;
	private String so2ica;
	private String icaestacion;

	public Datos() {
	}

	public Datos(Estaciones estaciones, Date fecha, Date hora) {
		this.estaciones = estaciones;
		this.fecha = fecha;
		this.hora = hora;
	}

	public Datos(Estaciones estaciones, Date fecha, Date hora, Double comgm3, Double co8hmgm3, Double nogm3, Double no2,
			String no2ica, Double noxgm3, Double pm10, String pm10ica, Double pm25, String pm25ica, Double so2,
			String so2ica, String icaestacion) {
		this.estaciones = estaciones;
		this.fecha = fecha;
		this.hora = hora;
		this.comgm3 = comgm3;
		this.co8hmgm3 = co8hmgm3;
		this.nogm3 = nogm3;
		this.no2 = no2;
		this.no2ica = no2ica;
		this.noxgm3 = noxgm3;
		this.pm10 = pm10;
		this.pm10ica = pm10ica;
		this.pm25 = pm25;
		this.pm25ica = pm25ica;
		this.so2 = so2;
		this.so2ica = so2ica;
		this.icaestacion = icaestacion;
	}

	public Integer getCodDatos() {
		return this.codDatos;
	}

	public void setCodDatos(Integer codDatos) {
		this.codDatos = codDatos;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public Double getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(Double comgm3) {
		this.comgm3 = comgm3;
	}

	public Double getCo8hmgm3() {
		return this.co8hmgm3;
	}

	public void setCo8hmgm3(Double co8hmgm3) {
		this.co8hmgm3 = co8hmgm3;
	}

	public Double getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(Double nogm3) {
		this.nogm3 = nogm3;
	}

	public Double getNo2() {
		return this.no2;
	}

	public void setNo2(Double no2) {
		this.no2 = no2;
	}

	public String getNo2ica() {
		return this.no2ica;
	}

	public void setNo2ica(String no2ica) {
		this.no2ica = no2ica;
	}

	public Double getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(Double noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public Double getPm10() {
		return this.pm10;
	}

	public void setPm10(Double pm10) {
		this.pm10 = pm10;
	}

	public String getPm10ica() {
		return this.pm10ica;
	}

	public void setPm10ica(String pm10ica) {
		this.pm10ica = pm10ica;
	}

	public Double getPm25() {
		return this.pm25;
	}

	public void setPm25(Double pm25) {
		this.pm25 = pm25;
	}

	public String getPm25ica() {
		return this.pm25ica;
	}

	public void setPm25ica(String pm25ica) {
		this.pm25ica = pm25ica;
	}

	public Double getSo2() {
		return this.so2;
	}

	public void setSo2(Double so2) {
		this.so2 = so2;
	}

	public String getSo2ica() {
		return this.so2ica;
	}

	public void setSo2ica(String so2ica) {
		this.so2ica = so2ica;
	}

	public String getIcaestacion() {
		return this.icaestacion;
	}

	public void setIcaestacion(String icaestacion) {
		this.icaestacion = icaestacion;
	}

}
