package modelo;
// Generated 17 ene. 2021 22:11:29 by Hibernate Tools 5.4.21.Final

/**
 * Datoshorarios generated by hbm2java
 */
public class Datoshorarios implements java.io.Serializable {

	private DatoshorariosId id;
	private Estaciones estaciones;
	private double comgm3;
	private double co8hmgm3;
	private double nogm3;
	private double no2gm3;
	private double noxgm3;
	private double pm10gm3;
	private double pm25gm3;
	private double so2gm3;

	public Datoshorarios() {
	}

	public Datoshorarios(DatoshorariosId id, Estaciones estaciones, double comgm3, double co8hmgm3, double nogm3,
			double no2gm3, double noxgm3, double pm10gm3, double pm25gm3, double so2gm3) {
		this.id = id;
		this.estaciones = estaciones;
		this.comgm3 = comgm3;
		this.co8hmgm3 = co8hmgm3;
		this.nogm3 = nogm3;
		this.no2gm3 = no2gm3;
		this.noxgm3 = noxgm3;
		this.pm10gm3 = pm10gm3;
		this.pm25gm3 = pm25gm3;
		this.so2gm3 = so2gm3;
	}

	public DatoshorariosId getId() {
		return this.id;
	}

	public void setId(DatoshorariosId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public double getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(double comgm3) {
		this.comgm3 = comgm3;
	}

	public double getCo8hmgm3() {
		return this.co8hmgm3;
	}

	public void setCo8hmgm3(double co8hmgm3) {
		this.co8hmgm3 = co8hmgm3;
	}

	public double getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(double nogm3) {
		this.nogm3 = nogm3;
	}

	public double getNo2gm3() {
		return this.no2gm3;
	}

	public void setNo2gm3(double no2gm3) {
		this.no2gm3 = no2gm3;
	}

	public double getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(double noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public double getPm10gm3() {
		return this.pm10gm3;
	}

	public void setPm10gm3(double pm10gm3) {
		this.pm10gm3 = pm10gm3;
	}

	public double getPm25gm3() {
		return this.pm25gm3;
	}

	public void setPm25gm3(double pm25gm3) {
		this.pm25gm3 = pm25gm3;
	}

	public double getSo2gm3() {
		return this.so2gm3;
	}

	public void setSo2gm3(double so2gm3) {
		this.so2gm3 = so2gm3;
	}

}
