package modelo;
// Generated 18 ene. 2021 15:51:17 by Hibernate Tools 5.4.21.Final

/**
 * Datoshorarios generated by hbm2java
 */
public class Datoshorarios implements java.io.Serializable {

	private DatoshorariosId id;
	private Estaciones estaciones;
	private Double comgm3;
	private Double co8hmgm3;
	private Double nogm3;
	private Double no2gm3;
	private Double noxgm3;
	private Double pm10gm3;
	private Double pm25gm3;
	private Double so2gm3;

	public Datoshorarios() {
	}

	public Datoshorarios(DatoshorariosId id, Estaciones estaciones) {
		this.id = id;
		this.estaciones = estaciones;
	}

	public Datoshorarios(DatoshorariosId id, Estaciones estaciones, Double comgm3, Double co8hmgm3, Double nogm3,
			Double no2gm3, Double noxgm3, Double pm10gm3, Double pm25gm3, Double so2gm3) {
		this.id = id;
		this.estaciones = estaciones;
		this.comgm3 = comgm3;
		this.co8hmgm3 = co8hmgm3;
		this.nogm3 = nogm3;
		this.no2gm3 = no2gm3;
		this.noxgm3 = noxgm3;
		this.pm10gm3 = pm10gm3;
		this.pm25gm3 = pm25gm3;
		this.so2gm3 = so2gm3;
	}

	public DatoshorariosId getId() {
		return this.id;
	}

	public void setId(DatoshorariosId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public Double getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(Double comgm3) {
		this.comgm3 = comgm3;
	}

	public Double getCo8hmgm3() {
		return this.co8hmgm3;
	}

	public void setCo8hmgm3(Double co8hmgm3) {
		this.co8hmgm3 = co8hmgm3;
	}

	public Double getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(Double nogm3) {
		this.nogm3 = nogm3;
	}

	public Double getNo2gm3() {
		return this.no2gm3;
	}

	public void setNo2gm3(Double no2gm3) {
		this.no2gm3 = no2gm3;
	}

	public Double getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(Double noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public Double getPm10gm3() {
		return this.pm10gm3;
	}

	public void setPm10gm3(Double pm10gm3) {
		this.pm10gm3 = pm10gm3;
	}

	public Double getPm25gm3() {
		return this.pm25gm3;
	}

	public void setPm25gm3(Double pm25gm3) {
		this.pm25gm3 = pm25gm3;
	}

	public Double getSo2gm3() {
		return this.so2gm3;
	}

	public void setSo2gm3(Double so2gm3) {
		this.so2gm3 = so2gm3;
	}

}
