package modelo;
// Generated 29 ene. 2021 15:52:31 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Espacios generated by hbm2java
 */
public class Espacios implements java.io.Serializable {

	private Integer codEspacio;
	private String nombre;
	private String descripcion;
	private String tipo;
	private String latitud;
	private String longitud;
	private Set ubicacioneses = new HashSet(0);
	private Set fotoesps = new HashSet(0);
	private Set favesps = new HashSet(0);

	public Espacios() {
	}

	public Espacios(String nombre) {
		this.nombre = nombre;
	}

	public Espacios(String nombre, String descripcion, String tipo, String latitud, String longitud, Set ubicacioneses,
			Set fotoesps, Set favesps) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.latitud = latitud;
		this.longitud = longitud;
		this.ubicacioneses = ubicacioneses;
		this.fotoesps = fotoesps;
		this.favesps = favesps;
	}

	public Integer getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(Integer codEspacio) {
		this.codEspacio = codEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	public Set getUbicacioneses() {
		return this.ubicacioneses;
	}

	public void setUbicacioneses(Set ubicacioneses) {
		this.ubicacioneses = ubicacioneses;
	}

	public Set getFotoesps() {
		return this.fotoesps;
	}

	public void setFotoesps(Set fotoesps) {
		this.fotoesps = fotoesps;
	}

	public Set getFavesps() {
		return this.favesps;
	}

	public void setFavesps(Set favesps) {
		this.favesps = favesps;
	}

}
