package modelo;
// Generated 17 ene. 2021 22:11:29 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Espacios generated by hbm2java
 */
public class Espacios implements java.io.Serializable {

	private Integer codEspacio;
	private String nombre;
	private String descripcion;
	private String tipo;
	private Set ubicacioneses = new HashSet(0);

	public Espacios() {
	}

	public Espacios(String nombre) {
		this.nombre = nombre;
	}

	public Espacios(String nombre, String descripcion, String tipo, Set ubicacioneses) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.ubicacioneses = ubicacioneses;
	}

	public Integer getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(Integer codEspacio) {
		this.codEspacio = codEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getUbicacioneses() {
		return this.ubicacioneses;
	}

	public void setUbicacioneses(Set ubicacioneses) {
		this.ubicacioneses = ubicacioneses;
	}

}
