package modelo;
// Generated 22 dic. 2020 18:00:36 by Hibernate Tools 5.4.21.Final

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones implements java.io.Serializable {

	private Integer codEst;
	private Municipios municipios;
	private String nombre;
	private String direccion;
	private Double latitud;
	private Double longitud;

	public Estaciones() {
	}

	public Estaciones(Municipios municipios, String nombre, String direccion, Double latitud, Double longitud) {
		this.municipios = municipios;
		this.nombre = nombre;
		this.direccion = direccion;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public Integer getCodEst() {
		return this.codEst;
	}

	public void setCodEst(Integer codEst) {
		this.codEst = codEst;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

}
