package modelo;
// Generated 1 feb. 2021 18:32:53 by Hibernate Tools 5.4.21.Final

/**
 * FavespId generated by hbm2java
 */
public class FavespId implements java.io.Serializable {

	private int codUsu;
	private int codEspacio;

	public FavespId() {
	}

	public FavespId(int codUsu, int codEspacio) {
		this.codUsu = codUsu;
		this.codEspacio = codEspacio;
	}

	public int getCodUsu() {
		return this.codUsu;
	}

	public void setCodUsu(int codUsu) {
		this.codUsu = codUsu;
	}

	public int getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(int codEspacio) {
		this.codEspacio = codEspacio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavespId))
			return false;
		FavespId castOther = (FavespId) other;

		return (this.getCodUsu() == castOther.getCodUsu()) && (this.getCodEspacio() == castOther.getCodEspacio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodUsu();
		result = 37 * result + this.getCodEspacio();
		return result;
	}

}
