package modelo;
// Generated 26 ene. 2021 15:55:13 by Hibernate Tools 5.4.21.Final

/**
 * FavmunId generated by hbm2java
 */
public class FavmunId implements java.io.Serializable {

	private int codUsu;
	private int codMuni;

	public FavmunId() {
	}

	public FavmunId(int codUsu, int codMuni) {
		this.codUsu = codUsu;
		this.codMuni = codMuni;
	}

	public int getCodUsu() {
		return this.codUsu;
	}

	public void setCodUsu(int codUsu) {
		this.codUsu = codUsu;
	}

	public int getCodMuni() {
		return this.codMuni;
	}

	public void setCodMuni(int codMuni) {
		this.codMuni = codMuni;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavmunId))
			return false;
		FavmunId castOther = (FavmunId) other;

		return (this.getCodUsu() == castOther.getCodUsu()) && (this.getCodMuni() == castOther.getCodMuni());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodUsu();
		result = 37 * result + this.getCodMuni();
		return result;
	}

}
