package modelo;
// Generated 29 ene. 2021 15:52:31 by Hibernate Tools 5.4.21.Final

/**
 * Favmun generated by hbm2java
 */
public class Favmun implements java.io.Serializable {

	private FavmunId id;
	private Municipios municipios;
	private Usuarios usuarios;

	public Favmun() {
	}

	public Favmun(FavmunId id, Municipios municipios, Usuarios usuarios) {
		this.id = id;
		this.municipios = municipios;
		this.usuarios = usuarios;
	}

	public FavmunId getId() {
		return this.id;
	}

	public void setId(FavmunId id) {
		this.id = id;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
