package modelo;
// Generated 22 dic. 2020 18:00:36 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private Integer codMuni;
	private String nombre;
	private String descripcion;
	private Integer codProv;
	private Set estacioneses = new HashSet(0);

	public Municipios() {
	}

	public Municipios(String nombre, String descripcion, Integer codProv, Set estacioneses) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codProv = codProv;
		this.estacioneses = estacioneses;
	}

	public Integer getCodMuni() {
		return this.codMuni;
	}

	public void setCodMuni(Integer codMuni) {
		this.codMuni = codMuni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getCodProv() {
		return this.codProv;
	}

	public void setCodProv(Integer codProv) {
		this.codProv = codProv;
	}

	public Set getEstacioneses() {
		return this.estacioneses;
	}

	public void setEstacioneses(Set estacioneses) {
		this.estacioneses = estacioneses;
	}

}
