package modelo;
// Generated 13 ene. 2021 20:28:42 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private int codMuni;
	private Provincias provincias;
	private String nombre;
	private String descripcion;
	private Set ubicacioneses = new HashSet(0);
	private Set estacioneses = new HashSet(0);

	public Municipios() {
	}

	public Municipios(int codMuni, Provincias provincias, String nombre) {
		this.codMuni = codMuni;
		this.provincias = provincias;
		this.nombre = nombre;
	}

	public Municipios(int codMuni, Provincias provincias, String nombre, String descripcion, Set ubicacioneses,
			Set estacioneses) {
		this.codMuni = codMuni;
		this.provincias = provincias;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.ubicacioneses = ubicacioneses;
		this.estacioneses = estacioneses;
	}

	public int getCodMuni() {
		return this.codMuni;
	}

	public void setCodMuni(int codMuni) {
		this.codMuni = codMuni;
	}

	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getUbicacioneses() {
		return this.ubicacioneses;
	}

	public void setUbicacioneses(Set ubicacioneses) {
		this.ubicacioneses = ubicacioneses;
	}

	public Set getEstacioneses() {
		return this.estacioneses;
	}

	public void setEstacioneses(Set estacioneses) {
		this.estacioneses = estacioneses;
	}

}
