package modelo;
// Generated 22 dic. 2020 18:00:36 by Hibernate Tools 5.4.21.Final

/**
 * Naturales generated by hbm2java
 */
public class Naturales implements java.io.Serializable {

	private Integer codEspacio;
	private String nombre;
	private String descripcion;

	public Naturales() {
	}

	public Naturales(String nombre, String descripcion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Integer getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(Integer codEspacio) {
		this.codEspacio = codEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
