package modelo;
// Generated 22 dic. 2020 18:00:36 by Hibernate Tools 5.4.21.Final

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private Integer codProv;
	private String nombre;

	public Provincias() {
	}

	public Provincias(String nombre) {
		this.nombre = nombre;
	}

	public Integer getCodProv() {
		return this.codProv;
	}

	public void setCodProv(Integer codProv) {
		this.codProv = codProv;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
