package modelo;
// Generated 1 feb. 2021 17:36:04 by Hibernate Tools 5.4.21.Final

/**
 * UbicacionesId generated by hbm2java
 */
public class UbicacionesId implements java.io.Serializable {

	private int codEspacio;
	private int codMuniAuto;

	public UbicacionesId() {
	}

	public UbicacionesId(int codEspacio, int codMuniAuto) {
		this.codEspacio = codEspacio;
		this.codMuniAuto = codMuniAuto;
	}

	public int getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(int codEspacio) {
		this.codEspacio = codEspacio;
	}

	public int getCodMuniAuto() {
		return this.codMuniAuto;
	}

	public void setCodMuniAuto(int codMuniAuto) {
		this.codMuniAuto = codMuniAuto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UbicacionesId))
			return false;
		UbicacionesId castOther = (UbicacionesId) other;

		return (this.getCodEspacio() == castOther.getCodEspacio())
				&& (this.getCodMuniAuto() == castOther.getCodMuniAuto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodEspacio();
		result = 37 * result + this.getCodMuniAuto();
		return result;
	}

}
