package modelo;
// Generated 13 ene. 2021 20:28:42 by Hibernate Tools 5.4.21.Final

/**
 * Ubicaciones generated by hbm2java
 */
public class Ubicaciones implements java.io.Serializable {

	private UbicacionesId id;
	private Municipios municipios;
	private Naturales naturales;

	

	public Ubicaciones(UbicacionesId id, Municipios municipios, Naturales naturales) {
		this.id = id;
		this.municipios = municipios;
		this.naturales = naturales;
	}

	public UbicacionesId getId() {
		return this.id;
	}

	public void setId(UbicacionesId id) {
		this.id = id;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public Naturales getNaturales() {
		return this.naturales;
	}

	public void setNaturales(Naturales naturales) {
		this.naturales = naturales;
	}

}
