package modelo;
// Generated 18 ene. 2021 10:51:22 by Hibernate Tools 5.4.21.Final

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer codUsu;
	private String nombre;
	private String password;

	public Usuarios() {
	}

	public Usuarios(String nombre, String password) {
		this.nombre = nombre;
		this.password = password;
	}

	public Integer getCodUsu() {
		return this.codUsu;
	}

	public void setCodUsu(Integer codUsu) {
		this.codUsu = codUsu;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
