package modelo;
// Generated 1 feb. 2021 18:32:53 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer codUsu;
	private String nombre;
	private String password;
	private Set fotoesps = new HashSet(0);
	private Set favesps = new HashSet(0);
	private Set favmuns = new HashSet(0);
	private Set fotomuns = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombre, String password) {
		this.nombre = nombre;
		this.password = password;
	}

	public Usuarios(String nombre, String password, Set fotoesps, Set favesps, Set favmuns, Set fotomuns) {
		this.nombre = nombre;
		this.password = password;
		this.fotoesps = fotoesps;
		this.favesps = favesps;
		this.favmuns = favmuns;
		this.fotomuns = fotomuns;
	}

	public Integer getCodUsu() {
		return this.codUsu;
	}

	public void setCodUsu(Integer codUsu) {
		this.codUsu = codUsu;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getFotoesps() {
		return this.fotoesps;
	}

	public void setFotoesps(Set fotoesps) {
		this.fotoesps = fotoesps;
	}

	public Set getFavesps() {
		return this.favesps;
	}

	public void setFavesps(Set favesps) {
		this.favesps = favesps;
	}

	public Set getFavmuns() {
		return this.favmuns;
	}

	public void setFavmuns(Set favmuns) {
		this.favmuns = favmuns;
	}

	public Set getFotomuns() {
		return this.fotomuns;
	}

	public void setFotomuns(Set fotomuns) {
		this.fotomuns = fotomuns;
	}

}
